BEGIN TRANSACTION;

ALTER TABLE broadcasts ALTER COLUMN receivers_count TYPE INT;
ALTER TABLE meetings ALTER COLUMN from_tele_id TYPE INT;
ALTER TABLE meetings ALTER COLUMN to_tele_id TYPE INT;

END TRANSACTION;